[package]
name = "tauri-desktop-template"
version = "0.1.0"
edition = "2024"
authors = ["Alfred Clark"]
description = "Desktop application development template based on Tauri and Svelte."
repository = "https://github.com/AlfredClark/tauri-desktop-template"
keywords = ["tauri", "desktop", "template"]
categories = ["gui"]
readme = "../README.md"
license = "GPL-3.0-only"

[lib]
name = "tauri_desktop_template_lib"
crate-type = ["rlib"]

[lints]
workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
