[workspace]
members = ["src-tauri"]
resolver = "2"

[workspace.lints.rust]
warnings = "warn"

[workspace.lints.clippy]
all = "warn"

[profile.dev]
debug = "full"

[profile.dev.package."*"]
opt-level = 1
debug = "line-tables-only"

[profile.release]
opt-level = "s"
debug = false
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
